<div id="buddypress">

	<?php bp_get_template_part( 'members/single/menu', 'members' ); ?>

	<div class="lorum">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer non elit mauris. Duis in gravida mi. Pellentesque ultricies dictum orci, id sagittis leo lobortis et. Fusce egestas, nisi nec posuere feugiat, erat mi ultricies sapien, at convallis mi dolor eu ipsum. Curabitur viverra placerat urna, sit amet ullamcorper lorem consectetur ac. Cras placerat tincidunt venenatis. Ut sodales neque quis odio volutpat in facilisis erat tristique. Quisque tempus, nibh sed sodales varius, orci nisi pharetra risus, id aliquam sapien metus vitae tortor. Fusce ac vestibulum justo. Aenean tempus, nisl nec mattis ullamcorper, augue metus mollis libero, sed mattis nulla augue ut velit. Duis sit amet sem nec justo malesuada mollis sed nec leo. Nam eleifend tempus arcu, quis convallis tellus semper vulputate.</p>

		<p>Aliquam vel erat diam. Quisque ullamcorper purus id eros faucibus in ultricies tortor pretium. Nam lorem felis, interdum ac dapibus sed, mollis ac nunc. Ut volutpat feugiat felis. Pellentesque bibendum tempor dui ut ornare. Nunc ac justo vehicula tortor accumsan euismod vel eu ipsum. Nullam neque neque, elementum a bibendum in, viverra et purus. Cras consectetur facilisis tellus, a suscipit ligula ornare sit amet. Vestibulum eu arcu ac urna ullamcorper porta. Donec suscipit risus at tellus luctus dapibus. Nam placerat ligula eu nunc facilisis viverra. Proin tincidunt bibendum iaculis. Vestibulum tempor felis sed augue auctor facilisis. Sed et ante id ipsum auctor eleifend vel ac odio. Nulla vitae mauris eget lacus convallis convallis.</p>

		<p>Cras fringilla molestie urna suscipit pellentesque. Quisque a nulla ut orci volutpat viverra at non elit. Vivamus rutrum justo id libero dignissim bibendum. Aenean porttitor lacinia eros id fringilla. Curabitur nec eros tempus quam eleifend facilisis elementum at ligula. Suspendisse potenti. Vestibulum justo massa, luctus ut consectetur nec, blandit vitae ipsum. Praesent at ullamcorper urna. Fusce bibendum orci eu est tempor sodales pretium felis placerat. Maecenas feugiat, erat sit amet vehicula ullamcorper, augue nibh dictum ligula, a convallis tellus turpis eu leo. Donec sed massa felis, quis condimentum risus. Praesent lacinia imperdiet arcu, et congue mauris ultricies ut. In laoreet, felis id ornare malesuada, elit ligula mattis erat, at viverra libero nisl ut odio. Aenean eget cursus ipsum.</p>

		<p>Morbi eget lobortis lorem. Donec ac mauris eu erat rutrum auctor. Mauris tincidunt sodales dui, in pharetra enim varius et. Nullam vehicula elementum lacus id pharetra. Duis elit tellus, consequat id pulvinar nec, sodales sed nunc. Praesent sit amet erat eros, eu aliquam sem. Fusce et felis purus, vel gravida enim. Mauris et libero leo, ut tincidunt nisi. Morbi id lectus quis dolor convallis tincidunt. Donec vitae euismod tellus. Phasellus vel scelerisque elit. Aliquam fringilla ullamcorper iaculis.</p>
	</div>

</div><!-- #buddypress -->